spring:
  application:
    name: s3-test

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    open-in-view: false
    generate-ddl: false
    hibernate:
      ddl-auto: validate

aws:
  bucket-name: ${BUCKET_NAME}

jwt:
  issuer: ${JWT_ISSUER}
  secret: ${JWT_SECRET}
  prefix: ${JWT_PREFIX}
  expiration: ${JWT_EXPIRATION}